CREATE TABLE `products` (
  `id` varchar(64) NOT NULL,
  `name` varchar(200) NOT NULL,
  `subtitle` varchar(200) NOT NULL DEFAULT '',
  `category` varchar(64) NOT NULL,
  `categoryLabel` varchar(64) NOT NULL,
  `price` int NOT NULL,
  `originalPrice` int,
  `priceRange` varchar(200),
  `depositRange` varchar(200),
  `image` text NOT NULL,
  `tags` json,
  `description` text,
  `story` text,
  `benefits` json,
  `suitableFor` json,
  `howToUse` json,
  `disclaimer` text,
  `crystalType` text,
  `color` varchar(100),
  `featured` boolean NOT NULL DEFAULT false,
  `active` boolean NOT NULL DEFAULT true,
  `sortOrder` int NOT NULL DEFAULT 0,
  `createdAt` timestamp NOT NULL DEFAULT (now()),
  `updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT `products_id` PRIMARY KEY(`id`)
);
