export const COOKIE_NAME = "app_session_id";
export const ONE_YEAR_MS = 1000 * 60 * 60 * 24 * 365;
export const AXIOS_TIMEOUT_MS = 30_000;
export const UNAUTHED_ERR_MSG = 'Please login (10001)';
export const NOT_ADMIN_ERR_MSG = 'You do not have required permission (10002)';
export const CUSTOM_PRODUCT_ID = "custom-deposit-product";
export const CUSTOM_PRODUCT_NAME = "客製化商品";
export const CUSTOM_TAROT_PRODUCT_ID = "tarot-crystal-deposit-product";
export const CUSTOM_PRODUCT_IDS = [CUSTOM_PRODUCT_ID, CUSTOM_TAROT_PRODUCT_ID];
